services:
  pubcraft:
    image: lamuri/pubcraft-editor:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
