services:
  pubcraft:
    image: lamuri/pubcraft-editor:latest
    environment:
      - NODE_ENV=production
      - SERVICE_FQDN_PUBCRAFT_8080
      - VITE_GITHUB_CLIENT_ID=${VITE_GITHUB_CLIENT_ID}
      - VITE_ORCID_CLIENT_ID=${VITE_ORCID_CLIENT_ID}
      - VITE_ORCID_PRODUCTION_URL=${VITE_ORCID_PRODUCTION_URL}
      - VITE_GITHUB_TOKEN_URI=${VITE_GITHUB_TOKEN_URL}
      - VITE_ORCID_TOKEN_URI=${VITE_ORCID_TOKEN_URL}
      - VITE_ORCID_API_URL=${VITE_ORCID_API_URL}
      - VITE_ORCID_REDIRECT_URL=${VITE_ORCID_REDIRECT_URL}
      - VITE_ORCID_SCOPE=${VITE_ORCID_SCOPE}
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
